# Generated by Django 4.2.2 on 2023-07-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartModel',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='CommentModel',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='CustomerModel',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='CustomerAddressModel',
            new_name='CustomerAddress',
        ),
        migrations.RenameModel(
            old_name='OrderModel',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'verbose_name_plural': 'customer addresses'},
        ),
    ]
