# Generated by Django 4.2.2 on 2023-09-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOptionPrice',
        ),
    ]
