# Generated by Django 4.2.2 on 2023-07-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_cartmodel_cart_rename_categorymodel_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
