# Generated by Django 4.2.2 on 2023-07-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_items',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_sum',
            new_name='sum',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_refunded',
            field=models.BooleanField(default=False, verbose_name='Refunded'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('On Delivery', 'On Delivery'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], default='Pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Createad At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Click', 'Click'), ('Payme', 'Payme'), ('Cash', 'Cash')], max_length=5),
        ),
    ]
