# Generated by Django 4.2.2 on 2023-07-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_order_address_order_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
