# Generated by Django 4.2.2 on 2023-07-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
    ]
